// Generated by CoffeeScript 1.3.3
var app, assets, express, gdata, http, io, port, srvr, studentsOnline, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

http = require('http');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return resp.render('index');
});

app.get('/student', function(req, resp) {
  return resp.render('student');
});

app.get('/teacher', function(req, resp) {
  return resp.render('teacher');
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

srvr = http.createServer(app);

io = (require('socket.io')).listen(srvr);

srvr.listen(port);

console.log("Listening on " + port + "\nPress CTRL-C to stop server.");

studentsOnline = function() {
  return io.of('/student').clients().length;
};

gdata = {
  clients: 0
};

io.sockets.manager.settings.blacklist = [];

io.of('/student').on('connection', function(socket) {
  gdata.clients = io.sockets.clients().length;
  socket.emit('online', {
    clients: studentsOnline()
  });
  socket.broadcast.emit('online', {
    clients: studentsOnline()
  });
  socket.on('edit', function(data) {
    gdata.text = data.text;
    socket.broadcast.emit('edit', gdata);
    socket.emit('online', {
      clients: studentsOnline()
    });
  });
  return socket.on('disconnect', function() {
    gdata.clients = studentsOnline();
    return socket.broadcast.emit('online', {
      clients: studentsOnline()
    });
  });
});

io.of('/teacher').on('connection', function(socket) {});

io.configure(function() {
  io.set("transports", ["xhr-polling"]);
  io.set("polling duration", 10);
  return io.set("sync disconnect on unload", true);
});
